# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [20]:
import torch


# Create random tensor
torch.manual_seed(42)
tensor=torch.randint(1,10,size=(7,7))
print(tensor+2)


tensor([[ 9,  8, 10,  7,  3,  5, 10],
        [ 8,  7,  5,  7,  7, 11,  3],
        [ 3,  7,  5,  7,  6,  7,  7],
        [11,  4,  8, 11,  7,  5,  3],
        [ 4,  4,  6,  6, 10, 10, 11],
        [10,  5,  8,  4,  6,  5,  6],
        [ 4,  6,  6, 11,  8,  7,  3]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [26]:
# Create another random tensor
torch.manual_seed(41)
tensor1=torch.randint(3,15,size=(1,7))
a=tensor.matmul(tensor1.T)
print(a)
# Perform matrix multiplication 


tensor([[377],
        [343],
        [309],
        [311],
        [384],
        [262],
        [315]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed


# Create two random tensors


# Matrix multiply tensors


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [34]:
# Set random seed
torch.manual_seed(2)

# Check for access to GPU

device = 'cuda' if torch.cuda.is_available() else 'cpu'

# Create two random tensors on GPU

tensor1=torch.rand(size=(2,3),device=device)
tensor2=torch.rand(size=(3,2),device=device)

print(tensor1 @ tensor2)


tensor([[0.8664, 0.4204],
        [0.9984, 0.4164]])



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [7]:
# Perform matmul on tensor_A and tensor_B


### 8. Find the maximum and minimum values of the output of 7.

In [30]:
# Find max
tensor.argmax()
# Find min
tensor.argmin()


tensor(4)

### 9. Find the maximum and minimum index values of the output of 7.

In [9]:
# Find arg max


# Find arg min



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [29]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_new=torch.rand(size=(1,1,1,7))
print(tensor_new)
# Remove single dimensions
tensor_new1=tensor_new.squeeze()

# Print out tensors and their shapes
print(f"Shape of the original tensor : {tensor_new.shape}")
print(f"Shape of the squeezed tensor : {tensor_new1.shape}")

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071]]]])
Shape of the original tensor : torch.Size([1, 1, 1, 7])
Shape of the squeezed tensor : torch.Size([7])
