In [40]:
with open('the_wizard_of_oz.txt','r',encoding='utf-8') as F:
    text=F.read()

chars=sorted(set(text))

In [41]:
string_to_int={ch: i for i,ch in enumerate(chars)}
int_to_string={i:ch for i,ch in enumerate(chars)}

encode=lambda s: [string_to_int[ch] for ch in s ]
decode=lambda l: ''.join([int_to_string[i] for i in l])

In [42]:
import torch
print(torch.__version__)
data = torch.tensor(encode(text),dtype=int)
print(len(encode(text)))
print(data)
blocksize=5
batchsize =4
n=int(0.8*len(data))
print(n)
train_data = data[:n]
validation_data = data[n:]
print(len(train_data))
ix=torch.randint(len(data)-blocksize,(batchsize,))
x=torch.stack([train_data[i:i+blocksize] for i in ix])
y=torch.stack([train_data[i+1:i+blocksize+1] for i in ix])
print(x)

1.12.1
207796
tensor([72, 34, 48,  ..., 54,  2, 71])
166236
166236
tensor([[49, 58,  1, 50, 55],
        [ 1, 60, 48, 45,  1],
        [60, 45, 58,  6,  1],
        [60, 45, 58,  1, 56]])


In [43]:
print(x)
print(y)

tensor([[49, 58,  1, 50, 55],
        [ 1, 60, 48, 45,  1],
        [60, 45, 58,  6,  1],
        [60, 45, 58,  1, 56]])
tensor([[58,  1, 50, 55, 61],
        [60, 48, 45,  1, 56],
        [45, 58,  6,  1, 52],
        [45, 58,  1, 56, 49]])


In [44]:
x=train_data[:blocksize]
#print(x)
y=train_data[1:blocksize+1]
#print(y)

for i in range(blocksize):
    context= x[:i+1]
    target = y[i]
    #print('when input is context' ,context , 'target is', target)


device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)


cpu


In [45]:
import time
start_time = time.time()
rand1=torch.rand(100,100,100,100).to(device=device)
rand2=torch.rand(100,100,100,100).to(device)
rand = rand1 @ rand2
end_time = time.time()

elapsed_time_torch = end_time -start_time
print(f'elpased time for torch is : {elapsed_time_torch:.8f}')

import numpy as np
start_time = time.time()
rand1=torch.rand(100,100,100,100).to(device=device)
rand2=torch.rand(100,100,100,100).to(device)
rand = np.multiply(rand1,rand2)
end_time = time.time()

elapsed_time_np = end_time -start_time
print(f'elpased time for numpy is : {elapsed_time_np:.8f}')

elpased time for torch is : 3.11053920
elpased time for numpy is : 2.91666937


In [46]:
probability=torch.tensor([0.1,0.9])
print(torch.multinomial(probability,10,True))
torch.cat((probability,torch.tensor([1])),dim=0)
out=torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5))==0,float('-inf'))
torch.exp(out)


tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [47]:
a=torch.tensor([[1,2,3],[3,4,5],[5,6,7],[7,8,9]])
b=torch.tensor([[[7,1,5],[8,2,10],[7,1,20],[8,2,10]],[[7,1,10],[8,2,15],[7,1,14],[8,2,15]]])
c=torch.tensor([[1,2],[3,4]])
d=torch.tensor([[[1,2],[3,4]],[[1,2],[3,4]],[[1,2],[3,4]],[[1,2],[3,4]]])
#print(a[0][0].item())
# print(a.ndim)
# print(a.shape)
# print(a)
# print(b.ndim)
# print(b.shape)
# print(b)
# print(c.ndim)
# print(c.shape)
# print(c)
# print(d.ndim)
# print(d.shape)
# print(d[0])
e=torch.rand(size=(3,224,224))
print(e.ndim)
torch.full_like(e,fill_value=10,dtype=torch.int16)[0][0]

3


tensor([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10, 10],

In [48]:
a=torch.randint(1,10,size=(3,2))
b=torch.randint(2,15,size=(2,3))
print(a)
print(b)
#print(a.matmul(b))
#print(a*b)
print(a.shape,b.shape)
print(a.min())
print(a.argmin())
print(a[0][0].item())

tensor([[5, 7],
        [1, 1],
        [2, 2]])
tensor([[10,  5,  7],
        [11,  3,  2]])
torch.Size([3, 2]) torch.Size([2, 3])
tensor(1)
tensor(2)
5


In [49]:
a=torch.arange(0,9)
#print(a)
reshaped=a.reshape((1,3,3))
print(reshaped)
stacked=torch.stack([reshaped,reshaped,reshaped],dim=1)
print(stacked.shape)
stacked_0=torch.stack([reshaped,reshaped,reshaped],dim=0)
print(stacked_0.shape)
reshaped[:,1,:]

tensor([[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]])
torch.Size([1, 3, 3, 3])
torch.Size([3, 1, 3, 3])


tensor([[3, 4, 5]])

In [50]:
a=torch.tensor([[1,2],[2,3],[3,4],[4,4]])
print(a)
print(a.shape)
print(a.ndim)
print(a.squeeze())
print(a.squeeze().size())
print(a.squeeze().ndim)
print(a.squeeze().unsqueeze(dim=-1))
print(a.squeeze().unsqueeze(dim=-1).size())
print(a.squeeze().unsqueeze(dim=-1).ndimension())

tensor([[1, 2],
        [2, 3],
        [3, 4],
        [4, 4]])
torch.Size([4, 2])
2
tensor([[1, 2],
        [2, 3],
        [3, 4],
        [4, 4]])
torch.Size([4, 2])
2
tensor([[[1],
         [2]],

        [[2],
         [3]],

        [[3],
         [4]],

        [[4],
         [4]]])
torch.Size([4, 2, 1])
3


##### Pytorch and Numpy Exercise #####

          Exercise to check if numpy and pytorch are exchangeable

In [1]:
import numpy
a=numpy.arange(1.,9.)
b=torch.arange(1.,9.)
a.transpose(0)


NameError: name 'torch' is not defined

In [9]:
import torch
print(torch.__version__)
device='cuda' if torch.cuda.is_available() else 'cpu'
#a=torch.arange(1.,10., device='cuda')

1.12.1
